### ISSUE TITLE
Can not build with Qt 6.7.0 for macOS

### ISSUE THREAD

**Issue by ghost** [villevoutilainen/ProgrammingPrinciplesAndPracticeUsingQt#6]
https://github.com/villevoutilainen/ProgrammingPrinciplesAndPracticeUsingQt/blob/a4fe2ee2d6598e891eb47720b827d41a6a6993dd/Graph.cpp#L159-L161

Getting error:
ProgrammingPrinciplesAndPracticeUsingQt/Graph.cpp:168: error: no matching constructor for initialization of 'Point'
ProgrammingPrinciplesAndPracticeUsingQt/Graph.cpp:168:25: error: no matching constructor for initialization of 'Point'
    , line(xy, d == x ? Point(xy.x + length, xy.y) : Point(xy.x, xy.y - length))
                        ^     ~~~~~~~~~~~~~~~~~~~
ProgrammingPrinciplesAndPracticeUsingQt/./PPP/Point.h:9:8: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
struct Point {
       ^
ProgrammingPrinciplesAndPracticeUsingQt/./PPP/Point.h:9:8: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 2 were provided
ProgrammingPrinciplesAndPracticeUsingQt/./PPP/Point.h:9:8: note: candidate constructor (the implicit default constructor) not viable: requires 0 arguments, but 2 were provided

Resolution:
Change it to use list initialization - 
line(xy, d == x ? Point{xy.x + length, xy.y} : Point{xy.x, xy.y - length})

**Comment by ConstCorrectness** [comment]
Get a C++20 compiler you ****

**Comment by villevoutilainen** [comment]
Manners.

Even the newest XCode seems to ship with clang++ 15, which doesn't have parenthesized aggregate init.

I'll patch this.

**Comment by villevoutilainen** [comment]
Fixed by https://github.com/villevoutilainen/ProgrammingPrinciplesAndPracticeUsingQt/commit/16780026211570e4c43e5aafbf0ae7222dd34374
